### ISSUE TITLE
Root Detection for Android

### ISSUE THREAD

**Issue by evanshortiss** [aerogear/aerogear-js-sdk#105]
## Description
I've tested the root checks on my Nexus 5 device and found that our default check is not sufficient for certain devices.

We are invoking `IRoot.isRooted()`, but on my device this doesn't catch the root. I need to invoke `IRoot. isRootedRedBeerWithoutBusyBoxCheck()` which correctly detected the root as did `IRoot.isRootedRedBeer()`.

I'm not 100% sure what solution is best here from an Android perspective. Maybe check both `isRootedRedBeer` and `isRootedRedBeerWithoutBusyBoxCheck`? If the `isRootedRedBeerWithoutBusyBoxCheck` returns false then assume it's a false positive per [this doc](https://github.com/scottyab/rootbeer/blob/master/README.md#false-positives)?

## Steps to reproduce
1. Root or obtain rooted Android Device
2. Invoke `return this.securityService.check(SecurityCheckType.notRooted)`
3. Verify that `check.passed` is false

**Comment by aidenkeating** [comment]
@evanshortiss Just to confirm (all the falses and trues get very confusing 😄).

This check (notRooted) should return:
* `false` if the device is rooted
* `true` if the device is not rooted.

So are you seeing it return `true` when the device is rooted?

I've seen this (https://github.com/scottyab/rootbeer/blob/master/README.md#false-positives) and we should probably take false positives into account. Just confirming the issue you're seeing and the documented issue are the same.

**Comment by evanshortiss** [comment]
@aidenkeating agreed, it is a little confusing! Here's my code:

```ts
  public async ionViewDidEnter () {
    const notRootedCheck = await this.sec.check(SecurityCheckType.notRooted)

    if (notRootedCheck.passed === false) {
      const alert = this.alertCtrl.create({
        title: 'Insecure Device',
        subTitle: 'We detected that this device is rooted. Running as root increases the likelihood of your device being compromised by malicious software designed to steal passwords and sensitive information. Continued use is at your own risk.',
        buttons: ['OK']
      })

      alert.present()
    }
  }
```

If the check fails i.e `notRooted` returns `passed === false` I want to show a warning.

On my rooted Nexus 5 this warning is not triggered as I would expect it to be. In a Pixel 2 emulator running Android API 26 it always reports that it's rooted - this might be an emulator quirk? From my limited testing it seems to be that `IRoot.isRooted()`(the internal call we use in this module) isn't sufficient and we also need to check `IRoot.isRootedRedBeer()`.

The following screenshots might help. You can see from the user agents that one is my rooted Nexus and the other is an emulator. 

![screen shot 2018-05-29 at 14 31 30](https://user-images.githubusercontent.com/1303687/40686723-2a425a80-634d-11e8-8f41-644c52bf8da0.png)
![screen shot 2018-05-29 at 14 31 57](https://user-images.githubusercontent.com/1303687/40686725-2a56ef18-634d-11e8-9d13-2f2bc085e1d5.png)

**Comment by evanshortiss** [comment]
> So are you seeing it return true when the device is rooted? If so, we do have an issue.

Bingo.

**Comment by ciaranRoche** [comment]
@evanshortiss thanks for all the extra details, I was finding it hard to test/recreate as you outlined, it seems to be a quirk with the emulators, I will add the `isRootedRedBeer()` function to our check and will ping you in the PR.

**Comment by evanshortiss** [comment]
@ciaranRoche yeah, I'm not sure what the deal is with emulators since they _always_ return `true` for all functions as seen above.

It's the real device that's the trickster since it evades the plain ole `isRooted()`

**Comment by ciaranRoche** [comment]
@evanshortiss I am going to merge the fix now, but I think we should keep this issue open. Next sprint we are bringing in a task on e2e verification of these security checks, ill make note of this issue and see if we can run those e2e steps on a real device for both this SDK and our Android SDK to ensure this issue is resolved.

**Comment by ciaranRoche** [comment]
@evanshortiss Just a quick update, we will be doing e2e testing on real devices and not emulators, so I think I will close this issue now, as anything found from the e2e testing will result in jira's being issued to rectify them.
