### ISSUE TITLE
iOS Auth SDK Issue without InAppBrowser

### ISSUE THREAD

**Issue by evanshortiss** [aerogear/aerogear-js-sdk#361]
## Bug Report

When performing a login to Keycloak without InAppBrowser on iOS I received a failure with this error in the console `TypeError: null is not an object (evaluating 'ref.addEventListener')`.

* **Affected Package(s)**: aerogear/auth
* **Package version(s)**: 2.4.0
* **Platform (e.g. Android/iOS)**: iOS
* **Platform Version**: 12.0 Simulator
* **Cordova Version**: CLI 9.0, cordova-ios@5.0.1
* **Node.js / npm versions**: 10.15 / 6.4

I created a simple Cordova application using `cordova create`, then added the SDK, bundled via browserify with the following:

```js
const app = agInit(config)

// initialise auth
const Auth = require('@aerogear/auth').Auth;
const authService = new Auth(app.config);
const initOptions = { onLoad: "login-required" };

authService.init(initOptions)
    .then(() => {
        // successful init & authentication
        alert('success')
    })
    .catch((err) => {
        // initialization error
        alert('fail')
        console.error(err)
    });
```

Running the app with this printed `TypeError: null is not an object (evaluating 'ref.addEventListener')`. After I added InAppBrowser the issue was resolved.

Maybe we need to check for InAppBrowser and report a better error depending on platform?

**Comment by evanshortiss** [comment]
> depending on platform

To clarify I say "depending on" platform since maybe this is not an issue on Android or certain iOS versions.

**Comment by wtrocki** [comment]
@evanshortiss This looks like documentation issue. By default, keycloak.js will use cordova adapter in Cordova environments that require these plugins. 

We can also pass explicitly to use default adapter. `{adapter:'default'}`, but I is recommended to use Cordova one or new `cordova-native`.

**Comment by wtrocki** [comment]
@evanshortiss Do you have time to contribute that change. I think we need note here: https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/_partials/keycloak/setting-up-the-idm-sdk.adoc

`cordova plugin add cordova-plugin-inappbrowser`

**Comment by evanshortiss** [comment]
> We can also pass explicitly to use default adapter. {adapter:'default'}, but I is recommended to use Cordova one or new cordova-native.

I don't understand this suggestion. What does `cordova-native` mean here? By `default` I assume you mean it tries to use `InAppBrowser`

@wtrocki, yeah I think documentation will help. I can add this.

I think it would also help to improve the error message if possible. Maybe perform a check for the plugin. If this check fails return an error like `The Cordova InAppBrowser plugin is required with the "default" adapter option. Please install the plugin or pass a different adapter`. Would this make sense?

**Comment by wtrocki** [comment]
Our SDK is just an almost empty wrapper for keycloak.js library. 
If we need something to be done - we doing it directly in keycloak. 
Default wrapper is not using cordova (it is simply website like behavior)
I actually tried that now and I'm not sure how this is happening because of library checks for the existence of Cordova and InAppBrowser:

https://github.com/keycloak/keycloak/blame/master/adapters/oidc/js/src/main/resources/keycloak.js#L1208

**Comment by evanshortiss** [comment]
> I actually tried that now and I'm not sure how this is happening because of library checks for the existence of Cordova and InAppBrowser

Yeah. It's strange. It seems like the issue I hit is that the return value of [this line](https://github.com/keycloak/keycloak/blame/master/adapters/oidc/js/src/main/resources/keycloak.js#L1212) doesn't support `addEventListener` on my device/iOS version?

**Comment by evanshortiss** [comment]
Put another way. Should this work on iOS without installing InAppBrowser?

**Comment by wtrocki** [comment]
This looks like Keycloak.js issue with recent IOS versions. 
I think IOS as a platform is very rarely tested for keycloak.js. 

I do not have the means (IOS device) now to confirm that issue.

**Comment by evanshortiss** [comment]
I'll open an Issue over there so and reference this one 👍

**Comment by wtrocki** [comment]
We have bumped version of keycloak.js 2 major versions. Going to verify that on IOS platform as well using automation tests. ping @jhellar @b1zzu

**Comment by b1zzu** [comment]
We test the kyecloak auth using the plugin inappbrowser, it is also documented that it is a requirement (https://docs.aerogear.org/aerogear/latest/identity-management.html#setting-up-sdk-idm in the Cordova tab), never tried with iOS but with Android, the authentication doesn't work without the inappbrowser plugin

**Comment by evanshortiss** [comment]
Thanks @b1zzu, the main issue is developer experience. Docs look good 👍

I think the error message `TypeError: null is not an object (evaluating 'ref.addEventListener')` that is thrown when InAppBrowser is missing can be improved.

Maybe I should make a PR to the `init` function of `Auth.ts` in this repo that checks `typeof cordova.InAppBrowser !== 'undefined'` and prints a warning or rejects a Promise with a better error?

**Comment by wtrocki** [comment]
Yep. We trying to contribute as much to keycloak.js. I will make that fix in keycloak.
