### ISSUE TITLE
error running scripts/docs.sh

### ISSUE THREAD

**Issue by finp** [aerogear/aerogear-js-sdk#71]
$ ./scripts/docs.sh  
returns:

Generate documentation for packages
lerna info version 2.11.0
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/home/pwright/repos/aerogear/aerogear-js-sdk/packages/metrics-cordova/src'

**Comment by wtrocki** [comment]
@finp Valid procedure to start doing anything in this repository is to:

```
npm i
npm run bootstrap
npm run build
```
Then we can execute:
```
./scripts/docs.sh
```
Regards
