### ISSUE TITLE
Broken Link for mobile-services.json 

### ISSUE THREAD

**Issue by mishraas** [aerogear/aerogear-js-sdk#94]
## Description
Link to example of mobile-services.json is broken in docs.
## Steps to reproduce
1. Navigate to https://github.com/aerogear/aerogear-js-sdk/blob/master/docs/auth/README.adoc#configuration-file
2. Scroll to 'Configuration File' section
3. Click on 'mobile-services.json' link

Actual: Error 404 page.
Expected: Link should be valid and should navigate to examples.
![screen shot 2018-05-15 at 11 15 54 am](https://user-images.githubusercontent.com/5410492/40034978-f060ca52-5831-11e8-8df6-7f064153a83d.png)

**Comment by aidenkeating** [comment]
@mishraas Thanks for creating an issue! I have created a PR #96 to resolve this.
