### ISSUE TITLE
Move plugin check into platformUtils

### ISSUE THREAD

**Issue by aidenkeating** [aerogear/aerogear-js-sdk#95]
## Description
Based on the comment here (https://github.com/aerogear/aerogear-js-sdk/pull/91#discussion_r188155974) we could refactor checking for plugins into a helper function in `platformUtils`. Instead of null checking we could then do something like 

```
IRoot = await platformUtils.getCordovaPlugin<IRoot>("IRoot");
```

**Comment by ciaranRoche** [comment]
Closing this issue, after looking into it we found that it does not add much value, over a regular null check due to having to cast type `any` to the plugins we want to get.
